src/domain/entities/atlassian-design.test.ts, src/domain/entities/atlassian-design.ts, src/infrastructure/figma/figma-client.ts, src/infrastructure/figma/figma-service.ts, src/infrastructure/figma/figma-transformer.test.ts, src/infrastructure/figma/figma-transformer.ts, src/infrastructure/figma/testing/mocks.ts, src/usecases/associate-entity-use-case.ts, src/usecases/disassociate-entity-use-case.ts, src/usecases/index.ts, src/usecases/types.ts, src/web/middleware/error-handler-middleware.ts, src/web/routes/atlassian-connect.ts, src/web/routes/entities/index.ts, src/web/routes/entities/integration.test.ts, src/web/routes/entities/types.ts
This PR is currently inclusive of changes in https://github.com/atlassian-labs/figma-for-jira/pull/55 which should be merged first.
* Added an `/entities/disassociateEntity` route and use case to handle disassociating Jira issues from Figma designs
* Standardised how ids are generated for `AtlassianDesign` entities. What's stored will always be a composite of `{fileKey}/{nodeId}`
* Consolidated `associateWith` and `disassociateFrom` types into a single `AtlassianEntity` type
=> MDTZ-941 Disassociate entity

.env.example, README.md, package.json, scripts/create-jwt.ts, src/infrastructure/jira/jira-client/jira-client.ts, src/infrastructure/jira/jira-client/jwt-utils.test.ts, src/infrastructure/jira/jira-client/jwt-utils.ts, src/infrastructure/jira/jira-client/testing/mocks.ts
Generating JWTs for local testing is pretty cumbersome. Added a new `npm run jwt:generate <request_method> <url>` script and new `.env` variables to streamline this a bit.
=> Add script to create JWTs

scripts/setup-jest.ts
This was causing flakiness in our integration tests that expect an error from a Promise.all call. If multiple endpoints inside a Promise.all call are mocked, there's no guarantee that all of the mocks will be hit if one of the Promises rejects, since Promise.all immediately halts execution on a single rejection.
=> NONE Remove global unused mock check to fix test flakiness

.runconfigs/Integration Tests.run.xml, .runconfigs/Unit Tests.run.xml, jest.config.integration.ts, jest.config.ts, prisma/migrations/20230922041702_initial/migration.sql, prisma/schema.prisma, scripts/setup-jest-integration-tests.ts, scripts/setup-jest.ts, src/domain/entities/associated-figma-design.ts, src/domain/entities/testing/mocks.ts, src/infrastructure/figma/figma-service.ts, src/infrastructure/repositories/associated-figma-design-repository.integration.test.ts, src/infrastructure/repositories/associated-figma-design-repository.ts, src/usecases/associate-entity-use-case.test.ts, src/usecases/associate-entity-use-case.ts, src/usecases/disassociate-entity-use-case.test.ts, src/usecases/disassociate-entity-use-case.ts, src/usecases/testing/index.ts, src/usecases/testing/mocks.ts, src/web/routes/entities/integration.test.ts, src/web/routes/figma/integration.test.ts
- **[Feature]:** Add `AssociatedFigmaDesign.associatedWithAri` field to track which Atlassian entity (e.g., Issue) a design is associated with. This knowledge is used to find and delete only a target `AssociatedFigmaDesign` record on a `/disassociateEntity` request.
- **[Feature]:** Update `/disassociateEntity` flow to delete `AssociatedFigmaDesign`.
- **[Improvement]:** Do not set up nock and Prisma for unit tests but only for integration tests.
- **[Improvement]:** Clean the database before each integration test.
- **[Improvement]:** Remove excessive integration tests for `/associateEntity` and `/disassociateEntity`.
- **[Improvement]:** Add unit test for `/associateEntity` and `/disassociateEntity`.
=> MDTZ-1017: Remove `AssociatedFigmaDesign` record on `/disassociateEntity` request

scripts/create-jwt.ts, src/infrastructure/webhook/webhook-service.test.ts, src/web/routes/figma/figma-router.ts, src/web/routes/figma/integration.test.ts, src/web/routes/figma/schemas.test.ts, src/web/routes/figma/schemas.ts, src/web/routes/figma/testing/mocks.ts, src/web/routes/figma/types.ts
Couple of small bugfixes:
- The first is to update the webhook event payload schema to make `file_key` and `file_name` optional for `PING` events
- When we subscribe to a webhook, some `PING` events are emitted immediately. These events don't have a `file_key` or `file_name`, so our schema validation was failing and we were returning a `400`
- The second fix is just to update the `create-jwt.ts` script to fix a renamed parameter
=> NONE Update webhook event payload schema and fix `jwt:generate` script

src/infrastructure/repositories/figma-team-repository.ts, src/usecases/index.ts, src/usecases/remove-figma-team-use-case.test.ts, src/usecases/remove-figma-team-use-case.ts, src/web/routes/teams/integration.test.ts, src/web/routes/teams/schemas.ts, src/web/routes/teams/teams-router.ts, src/web/routes/teams/types.ts, src/web/testing/mocks.ts
Adds an endpoint (`DELETE /teams/configure`) for removing a configured `FigmaTeam`. The endpoint will attempt to delete the corresponding webhook, then delete the `FigmaTeam` record, regardless of whether or not deleting the webhook succeeded.
@akostevich-atlassian I will leave the refactoring updating the FigmaTeam auth status that we discussed to a separate PR, since it's not really related to these changes.
=> MDTZ-974 Add endpoint for removing a configured Figma team

src/infrastructure/figma/errors.ts, src/infrastructure/figma/figma-client/testing/mocks.ts, src/infrastructure/figma/figma-service.test.ts, src/infrastructure/figma/figma-service.ts, src/infrastructure/figma/figma-webhook-service.test.ts, src/infrastructure/figma/figma-webhook-service.ts, src/usecases/handle-figma-file-update-event-use-case.test.ts, src/usecases/handle-figma-file-update-event-use-case.ts, src/web/middleware/error-handler-middleware.ts, src/web/routes/figma/integration.test.ts
This PR resolves two tickets for the webhook events endpoint:
**MDTZ-1019** 
Updated how we fetch design data to only make one API request, passing in a list of node IDs. Previously we were firing an API request for each `AssociatedFigmaDesign` record.
To facilitate this, the `FigmaService.fetchDesignsByIds` method was added that accepts a `FigmaDesignIdentifier[]` and parses the file response into an `AtlassianDesign[]`.
**MDTZ-1034**
Updated error handling to update FigmaTeam auth status whenever we get a FigmaServiceCredentialsError when hitting Figma APIs.
=> MDTZ-1019 / MDTZ-1034 Refactor handle file update event use case

scripts/create-jwt.ts, src/web/routes/lifecycle-events/integration.test.ts, src/web/routes/lifecycle-events/lifecycle-events-router.ts, src/web/routes/lifecycle-events/schemas.ts, src/web/routes/lifecycle-events/testing/mocks.ts, src/web/routes/lifecycle-events/types.ts
- **[Fix]:** Fixes the issue with the "Uninstalled" event schema requiring `sharedSecret`. Jira does not send `sharedSecret` on the "Uninstalled" event (see more detail [here](https://developer.atlassian.com/cloud/jira/platform/connect-app-descriptor/#lifecycle)) -- therefore, `/lifecycleEvents/uninstalled` always returned an error. For extra safety and extensibility, the PR separates the types and schemas for lifecycle events due to minor differences among them.
- **[Improvement]:** Updates `createJwtToken` development utility to handle query parameters. This change allows to generate a token for an `auth/checkAuth` request:
```sh
npm run jwt:generate \
GET "${BASE_URL}/auth/checkAuth?userId=${ATLASSIAN_USER_ID}"
```
=> NONE: Fix "Uninstalled" event handling

src/infrastructure/figma/figma-client/testing/mocks.ts, src/infrastructure/figma/figma-service.test.ts, src/infrastructure/figma/figma-service.ts, src/infrastructure/jira/jira-client/testing/mocks.ts, src/web/routes/entities/integration.test.ts, src/web/routes/figma/integration.test.ts, src/web/routes/lifecycle-events/integration.test.ts, src/web/routes/teams/integration.test.ts, src/web/testing/connect-api-mock.ts, src/web/testing/figma-api-mocks.ts, src/web/testing/jira-api-mocks.ts
- **[Improvement]:** Updates test utilities for mocking endpoints (with Nock) to provide consistent contact.
```ts
export const mockXxxEndpoint = ({
baseUrl,
param1,
param2,
request,
response = generateXxxResponse(),
status = HttpStatusCode.Ok,
}: {
// ...
}) => {
// ...
}
```
- **[Improvement]:** Updates some integration tests to assert requests to external services.
- **[Improvement]:** Applies minor refactoring to tests.
=> NONE: Refactor integration tests

src/domain/entities/figma-team.ts, src/domain/entities/testing/mocks.ts, src/infrastructure/repositories/figma-team-repository.ts, src/usecases/handle-figma-file-update-event-use-case.ts, src/usecases/remove-figma-team-use-case.test.ts, src/usecases/remove-figma-team-use-case.ts, src/usecases/uninstalled-use-case.test.ts, src/usecases/uninstalled-use-case.ts, src/web/routes/teams/integration.test.ts
The PR addresses https://github.com/atlassian-labs/figma-for-jira/pull/83#discussion_r1340880224 from another PR.
- **[Improvement]:** Adds a `FigmaTeam.adminInfo` property.
- **[Improvement]:** Update the `FigmaTeam` consumer code to leverage a new property instead of a manual construction of `ConnectUserInfo` object.
=> NONE: Add `FigmaTeam.adminInfo` to simplify `FigmaTeam` consumer code

src/common/stringUtils.test.ts, src/common/stringUtils.ts, src/infrastructure/ajv.test.ts, src/infrastructure/ajv.ts, src/infrastructure/jira/jira-client/jira-client.test.ts, src/infrastructure/jira/jira-client/jira-client.ts, src/infrastructure/jira/jira-service.test.ts, src/infrastructure/jira/jira-service.ts
When we write the `attached-design-url-v2` issue property, we check the existing value before updating, as we must include previously associated URLs in the new value. Since anyone with issue access can write any issue property, we also check that the issue property value is in the expected format.
This PR reworks how we update the `attached-design-url-v2` issue property. Instead of throwing an error when the value is in an unexpected format, we overwrite it with the new issue property value instead.
=> MDTZ-1007 Overwrite 'attached-design-url-v2' issue property

src/usecases/handle-figma-file-update-event-use-case.ts, src/web/routes/figma/integration.test.ts
This fixes the app fetching the Figma file and submitting an empty list to `/rest/designs/1.0/bulk` when there are no associated designs for the file key specified in the webhook event payload.
=> NONE Handle no associated designs in webhook event handler

admin/vite.config.ts, src/atlassian-connect.ts, src/web/routes/admin/admin-router.ts, src/web/routes/admin/auth/auth-router.ts, src/web/routes/admin/auth/index.ts, src/web/routes/admin/auth/integration.test.ts, src/web/routes/admin/auth/types.ts, src/web/routes/admin/teams/index.ts, src/web/routes/admin/teams/integration.test.ts, src/web/routes/admin/teams/schemas.ts, src/web/routes/admin/teams/teams-router.ts, src/web/routes/admin/teams/types.ts, src/web/routes/router.ts, src/web/routes/teams/index.ts
The PR addresses an issue with the `checkAuth` endpoint not being accessible from the admin UI. Please, see https://github.com/atlassian-labs/figma-for-jira/pull/106#issuecomment-1774339465 for more detail.
- **feat:** Adds a new `/admin/auth/checkAuth` endpoint that can be used to check an admin's auth status from the admin UI.
- **refactor:** Groups all admin-related endpoints under the `/admin` path:
- `GET /admin/auth/checkAuth`
- `GET /admin/teams` (before, `GET /teams`)
- `POST /admin/teams/:teamId/connect` (before, `POST /teams/:teamId/connect`)
- `POST /admin/teams/:teamId/disconnect` (before, `POST /teams/:teamId/disconnect`)
- **refactor:** Mounts the routes for admin frontend resources under `static/admin` to distinguish the API and static resource routes.
The PR adds a new …
=> NONE: Add `/admin/auth/checkAuth` endpoint. Group admin endpoints under `/admin`.

src/infrastructure/ajv.ts, src/infrastructure/jira/jira-service.test.ts
For the ` ingested-design-urls` issue property schema validation was failing as the value was not a string. Updated the `parseJsonOfSchema` function to handle this
=> MDTZ-1081: Fixed string validation error for ingested-design-urls issue property

src/infrastructure/jira/jira-client/jira-client.test.ts, src/infrastructure/jira/jira-client/jira-client.ts, src/infrastructure/jira/jira-client/schemas.ts, src/infrastructure/jira/jira-client/testing/mocks.ts, src/infrastructure/jira/jira-client/types.ts, src/infrastructure/jira/jira-service.test.ts, src/infrastructure/jira/jira-service.ts, src/web/middleware/jira/index.ts, src/web/middleware/jira/jira-admin-only-auth-middleware.ts, src/web/routes/admin/admin-router.ts, src/web/routes/admin/auth/integration.test.ts, src/web/routes/admin/teams/integration.test.ts, src/web/routes/auth/integration.test.ts, src/web/testing/jira-api-mocks.ts
-**feat:** Implements `jiraAdminOnlyAuthMiddleware` to restrict access to endpoints to Jira admins.
-**feat:** Applies `jiraAdminOnlyAuthMiddleware` to all `/admin` endpoints.
-**test:** Applies minor refactoring to related integration tests.
=> MDTZ-1072: Make `/admin` endpoints accessible only by Jira admins

jest.config.unit.ts
The regex bit (?!.*integration.*) checks that we don't match a test like integration.test.ts.
Our copy of this repo lives under the directory `integrations/figma-for-jira`. Currently, this regex inadvertently matches all tests within integrations/figma-for-jira because the folder name has the string integration
To fix the regex, I added a check to exclude integration. vs. just the string integration.
I checked that `npm run test:unit` runs both in this copy and in our copy.
=> [tests] Tweak the regex for jest unit tests to explicitly check for `integration.`

src/infrastructure/jira/jira-client/jira-client.test.ts, src/infrastructure/jira/jira-client/jira-client.ts, src/infrastructure/jira/jira-service.test.ts, src/infrastructure/jira/jira-service.ts, src/usecases/disconnect-figma-team-use-case.test.ts, src/usecases/disconnect-figma-team-use-case.ts, src/web/routes/admin/teams/integration.test.ts
- **fix:** Update `JiraClient.setAppProperty` to 
- accept `application/json` from the [Set app property](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-app-properties/#api-rest-atlassian-connect-1-addons-addonkey-properties-propertykey-put) endpoint.
- explicitly serialize "[Set app property](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-app-properties/#api-rest-atlassian-connect-1-addons-addonkey-properties-propertykey-put)" request to JSON as it expects "a valid, non-empty JSON blob".
- **refactor:** Reduce technical debt by updating `JiraClient.setIssueProperty` by analogue with `JiraClient.setAppProperty`. Replaces `superStringify` (confirmed earlier with @atlasctz) with explicit JSON encoding in `JiraClient`.
=> NONE: Resolve the issue with setting Connect app property.

src/infrastructure/jira/jira-service.test.ts, src/infrastructure/jira/jira-service.ts, src/usecases/connect-figma-team-use-case.test.ts, src/usecases/connect-figma-team-use-case.ts, src/usecases/disconnect-figma-team-use-case.test.ts, src/usecases/disconnect-figma-team-use-case.ts, src/web/routes/admin/teams/integration.test.ts
- **feat:** Sets `is-configured` app property key according to the current contract.
=> NONE: Set `is-configured` app property key according to the current contract

prisma/migrations/20230927081534_initial/migration.sql, prisma/schema.prisma
We are setting up the DB for the figma-for-jira app in staging and prod. In the future, we may want to use the same DB for other integrations. This PR renames the DB tables to have the `jira_` prefix so we can have unique DB table names.
⚠️ After this change merges, you will need to drop and regenerate your local DB:
```
npm run db:reset:dev
npm run db:generate
```
- I checked my local DB to confirm the tables show up as expected
```
docker exec -it figma-for-jira-db bash
psql figma_for_jira -U figma_for_jira_app
```
- Unit / integration tests should pass.
- I tested installing the app locally, and it worked as expected.
=> [db] Rename DB tables to have the jira_ prefix

src/domain/entities/figma-design-identifier.test.ts, src/domain/entities/figma-design-identifier.ts
Updated parsing logic of Figma URLs to account for prototype links and allow the file key to be extracted. 
Tested change with the local app in staging: https://www.loom.com/share/fd9e07c8f87144da86cb5bf418e7d602
=> MDTZ-1150: Updated Figma URL parsing to handle prototype links

static/auth-result/index.html
The variable `errorType` is not defined. This PR removes it.
```
auth-result/?success=false:33 Uncaught ReferenceError: errorType is not defined
at auth-result/?success=false:33:17
```
This is resulting in an error on the /static/auth-result/?success=false after completing oauth.
=> [fix] Remove undefined variable errorType

src/infrastructure/figma/figma-client/figma-client.ts, src/infrastructure/figma/figma-client/types.ts, src/infrastructure/figma/figma-service.test.ts, src/infrastructure/figma/figma-service.ts, src/usecases/associate-entity-use-case.test.ts, src/usecases/associate-entity-use-case.ts, src/usecases/disassociate-entity-use-case.test.ts, src/usecases/disassociate-entity-use-case.ts
- **feat:** Update `FigmaService.deleteDevResource` to not throw an error if a Dev Resource was concurrently deleted by another user.
- **refactor** Renames `FigmaService.createDevResourceForJiraIssue` to `FigmaService.tryCreateDevResourceForJiraIssue` to highlight that it creates a Dev Resource on a best-efforts basis.
- **refactor:** Updates `FigmaClient.getDevResources` to accept `nodeIds` as an array instead of a comma separated string. See https://www.figma.com/developers/api#get-dev-resources-endpoint (`node_ids` query parameter) for more detail.
- **tests:** Adds unit tests for `FigmaService.deleteDevResource`.
=> NONE: Improve reliability and consistency

.github/workflows/actions.yml, Dockerfile
Images referenced from a Dockerfile FROM should always be pinned to an exact SHA-256 hash. This gives us confidence that builds are repeatable and changes to base images are always obvious in CI. This is essentially Docker's equivalent of a "lockfile". Same applies to gh actions
- assert that docker build still works as expected
- assert that the gh action runs as expected
=> NONE: pin hashes for images and actions

admin/src/pages/teams/connected-teams-list.tsx, admin/src/pages/teams/disconnect-team-unauthorized-section-message.tsx, admin/src/pages/teams/disconnect-team-warning-modal.tsx, admin/src/pages/teams/generic-error-section-message.tsx
Adds the logic for showing a warning modal when disconnecting a team.
https://github.com/atlassian-labs/figma-for-jira/assets/6136959/03570fc5-a241-46ae-8e42-f47db9281e74
- try to disconnect a team
- assert that the modal shows up
- assert that the cancel closes the modal and disconnect disconnects the team
- hard code an error in the disconnect request
- assert that on error, the modal closes and the appropriate error message is rendered
=> NONE: Show warning modal when disconnecting a team

admin/package.json, admin/src/pages/teams/connected-teams-list.tsx, admin/src/pages/teams/disconnected-team-flag.tsx, package-lock.json
Adds the logic for showing a flag when a team has been disconnected (See video)
https://github.com/atlassian-labs/figma-for-jira/assets/6136959/a734c972-bf06-469d-b93d-6c95954a5ab2
- assert that the flag shows up after a team has been disconnected
- assert that clicking "Got it" closes the flag
- assert that clicking "Undo" reconnects the team
=> NONE: Show a flag after disconnecting a team

admin/package.json, admin/src/hooks/index.ts, admin/src/hooks/useAuthenticate.ts, admin/src/pages/auth/auth-page.tsx, admin/src/pages/teams/figma-teams-connector.tsx, package-lock.json
Adds logic for auto closing the post auth page. I added zod as a dependency to safely parse the messages we get from the post auth page.
- go through the login flow and assert that after going through the grant flow, the tab auto closes
- repeat for the switch user flow
=> NONE: Add logic for auto closing the post auth page

admin/src/pages/teams/figma-teams-connector.tsx
This PR updates the logic for clicking `Change Figma account` to navigate directly to Figma's account selector page instead of the auth grant screen.
- Click `Change Figma account`
- Assert that it navigates to the account picker page in Figma
- Assert that this works even when you're only logged into 1 account (screenshot)
- Assert that after selecting an account, it will go through the auth grant flow
=> FABB-4: Update switch accounts flow to navigate directly to the accounts picker

src/atlassian-connect.ts
Read over the documentation on https://developer.atlassian.com/cloud/jira/platform/modules/admin-page/ and https://developer.atlassian.com/cloud/jira/platform/modules/page/
Looks like it was rendering "Get started" because we were using a `postInstallPage`. To have it render "Configure", we should be using a `configurePage`.
- uninstall/reinstall the app
- assert that it now shows configure instead of get started
- assert that clicking the configure button navigates to the webhook config page
=> FABB-22: Rename get started -> configure

.env.example, package-lock.json, package.json, src/app.ts, src/config/config.ts, src/config/testing/mocks.ts, src/infrastructure/tracer.ts, src/web/routes/router.ts
When we deploy the figma-for-jira app, we use Datadog to track the service metric / logs. This PR adds Datadog to the public repo. In practice, this should be a no-op.
=> [logging] Add the Datadog tracer 

src/web/routes/router.ts
In a previous PR, I added the Datadog tracer library. https://github.com/atlassian-labs/figma-for-jira/pull/154/files
I accidentally added it twice. This PR removes the duplicate import. There is already an entrypoint in src/app.ts.
=> [logging] Remove duplicate tracer

src/common/url-utils.test.ts, src/common/url-utils.ts, src/domain/entities/testing/mocks.ts, src/infrastructure/figma/figma-client/figma-client.ts, src/infrastructure/figma/transformers/utils.test.ts, src/infrastructure/figma/transformers/utils.ts, src/infrastructure/jira/inbound-auth/connect-key-server-client.ts, src/infrastructure/jira/jira-client/jira-client.test.ts, src/infrastructure/jira/jira-client/jira-client.ts, src/infrastructure/jira/jira-service.test.ts, src/infrastructure/jira/jira-service.ts, src/web/routes/entities/integration.test.ts
- **feat:** Exclude a Figma File name from the design URL as it is not required and is subject to change. The app still include File name in the URL written to the `attached-design-url` Issue Property for compatibility with "Jira" widget in Figma (which extracts a name from the URL).
- **feat:** Encode dynamic URL path parameters using `encodeURIComponent` when construct URLs (e.g., in API clients).
- **test:** Add unit tests for utility functions responsible for constructing Figma URLs.
=> MDTZ-1175: Remove Figma File name from design URL. Encode URL path parameters in API clients.

src/atlassian-connect.ts
- **feat:** Use the `issue-view-designs-panel` feature flag to manage the transition from the old to new experience.
- **feat:** Do not show admin UI when the `issue-view-designs-panel` feature is disabled.
=> NONE: Use a feature flag to control the availability of old panel and admin UI

src/web/middleware/http-logger-middleware.ts
- **feat:** Exclude potentially sensitive information from HTTP request/response logs (e.g., HTTP headers, remote address, etc.).
The app will log the following information:
- Request
- ID
- HTTP method
- URL
- Responses
- HTTP Code
- Response time
- Thrown error (all fields)
An example of a successful `/atlassian-connect.json` request:
An example of an unsuccessful `/admin/teams/:teamId/connect` request:
=> NONE: Exclude potentially sensitive information from HTTP request/response logs

src/infrastructure/figma/figma-client/types.ts, src/infrastructure/figma/figma-service.ts, src/web/routes/entities/integration.test.ts, src/web/routes/figma/integration.test.ts
- **feat:** Use the `depth=0` query parameter with the `GET /v1/files/:key` endpoint to exclude unnecessary child nodes, and therefore, reduce a response payload and network latency.
=> MDTZ-1186: Exclude unnecessary child nodes from Figma API response

src/common/predicates.test.ts, src/common/predicates.ts, src/infrastructure/figma/figma-service.test.ts, src/infrastructure/figma/figma-service.ts, src/infrastructure/figma/transformers/figma-node-transformer.test.ts, src/infrastructure/figma/transformers/figma-node-transformer.ts, src/usecases/handle-figma-file-update-event-use-case.test.ts, src/usecases/handle-figma-file-update-event-use-case.ts, src/web/routes/figma/integration.test.ts, src/web/routes/figma/schemas.test.ts, src/web/routes/figma/schemas.ts, src/web/routes/figma/testing/mocks.ts, src/web/routes/figma/types.ts
- **fix:** Skips Figma `FILE_UPDATE` event processing when Figma File is not found (an edge case when a Figma File is deleted right after a webhook is triggered) and return `HTTP 200`.
- **fix:** Does not fail Figma `FILE_UPDATE` event processing when a File does not contain some Nodes, previously linked to Jira issues. Skips event processing for these Nodes but processes the remaining. 
- **fix:** Returns `HTTP 200` for Figma `FILE_DELETE` event, which is delivered within the `FILE_UPDATE` subscription. According to Figma [docs](https://www.figma.com/developers/api#webhooks-v2-events), "If you subscribe to FILE_UPDATE, you automatically get these notifications.".
=> NONE: Improve webhook reliability

src/infrastructure/figma/transformers/figma-file-meta-transformer.test.ts, src/infrastructure/figma/transformers/figma-file-meta-transformer.ts, src/infrastructure/figma/transformers/figma-file-transformer.test.ts, src/infrastructure/figma/transformers/figma-file-transformer.ts, src/infrastructure/figma/transformers/figma-node-transformer.test.ts, src/infrastructure/figma/transformers/figma-node-transformer.ts, src/infrastructure/figma/transformers/utils.test.ts, src/infrastructure/figma/transformers/utils.ts, src/infrastructure/jira/jira-service.test.ts, src/infrastructure/jira/jira-service.ts, src/web/routes/entities/integration.test.ts, tsconfig.json
- **fix:** Resolves the issue with the "Jira" widget showing an already unlinked design.
- **fix:** Resolves the issue with the "Jira" widget showing some special symbols in a design name incorrectly.
- **refactor:** Removes unused parameter from Figma design transformation utilities.
=> FABB-50: Improve compatibility with the "Jira" widget in Figma

src/infrastructure/jira/jira-client/jira-client.test.ts, src/infrastructure/jira/jira-client/jira-client.ts, src/infrastructure/jira/jira-client/schemas.ts, src/infrastructure/jira/jira-client/testing/mocks.ts, src/web/testing/jira-api-mocks.ts
Adds support for JSM & JWM
Jira Software Cloud (JSW) APIs do not support Jira Service Management (JSM) or Jira Work Management (JWM): https://developer.atlassian.com/cloud/jira/software/rest/api-group-issue/#api-rest-agile-1-0-issue-issueidorkey-get
Jira Cloud Platform APIs support all flavours of Jira: https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-get
This PR changes the API used to fetch the Jira issue so that associating a Figma design works in JSM and JWM.
Previously attempting to associate a design resulted in an error with a 403 response from the Jira issue API:
With this change we are able to associate a design in JSM and JWM:
https://www.loom.com/share/23cdaf21b66f4a4a81e876476af8dc64
=> MDTZ-1095 Use Jira platform API instead of JSW API

.eslintignore, admin/jest.config.ts, admin/package.json, admin/src/pages/auth/auth-page.tsx, admin/src/pages/teams/figma-teams-connector.tsx, admin/src/utils/parseTeamIdFromFigmaUrl.test.ts, package-lock.json, package.json, src/common/schema-validation.test.ts, src/common/schema-validation.ts, src/infrastructure/axios-utils.ts, src/infrastructure/figma/figma-client/schemas.ts, src/infrastructure/figma/figma-client/types.ts, src/infrastructure/figma/figma-service.test.ts, src/infrastructure/figma/figma-service.ts, src/infrastructure/http-client-errors.ts, src/usecases/connect-figma-team-use-case.test.ts, src/usecases/connect-figma-team-use-case.ts, src/usecases/errors.ts, src/web/middleware/error-handler-middleware.ts, src/web/routes/admin/teams/integration.test.ts, src/web/testing/figma-api-mocks.ts, tsconfig.json
The PR addresses comments in https://github.com/atlassian-labs/figma-for-jira/pull/153.
- **refactor:** Handles paid plan-related `HTTP 400` errors from Figma API in `FigmaService.createFileUpdateWebhook` instead of `connectFigmaTeamUseCase`. See here for more detail: https://github.com/atlassian-labs/figma-for-jira/pull/153#discussion_r1398662659.
- **refactor:** Returns [HTTP 402 Payment Required](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402) when a user connects Figma teams with no paid plan. This allows the frontend to easily distinguish plan-related errors from others.
- **feat:** Updates UI messages according to the latest requirements. 
- **test:** Adds additional unit and integration tests.
=> FABB-2: Handle when users connect Figma teams with no paid plan

static/issue-panel/issue-panel.js
This PR updates our legacy add on experience to use an iframe for the network requests it makes to `www.figma.com/api/*` to use an iframe we host off of `www.figma.com`.
The iframe will call `window.parent.postMessage()` with the response from the api call. For security reasons, we limit the `host` to `figma-for-jira.figma.com` for these messages.
We only include the transpiled JS code in this codebase, but the original typescript code for this looks like:
```ts
async function fetchWithIframe<T>(params: Params): Promise<T> {
return new Promise((resolve, reject) => {
const iframe = document.createElement('iframe')
iframe.style.display = 'hidden'
iframe.style.width = '0px'
iframe.style.height = '0px'
function onMessage(event: MessageEvent) {
if (event.origin !== 'https://www.figma.com') { …
```
=> NONE: fix the legacy add-on's network requests to figma.com

src/infrastructure/figma/figma-service.test.ts, src/infrastructure/figma/figma-service.ts, src/infrastructure/figma/transformers/figma-node-transformer.test.ts, src/infrastructure/figma/transformers/figma-node-transformer.ts, src/usecases/associate-design-use-case.test.ts, src/usecases/associate-design-use-case.ts, src/usecases/disassociate-design-use-case.ts, src/usecases/errors.ts, src/web/middleware/error-handler-middleware.ts, src/web/routes/entities/integration.test.ts
- **feat:** Updates the `POST entities/associateEntity` endpoint to return `HTTP 404 Not Found` when a Figma File or Node does not exist.
- **refactor:** Applies minor improvements to `FigmaService`.
=> FABB-69: Return `HTTP 404` when associate a non-existent Figma File or Node

src/infrastructure/figma/figma-service.test.ts, src/infrastructure/figma/figma-service.ts, src/usecases/connect-figma-team-use-case.ts
Suppose you input an invalid team ID when you connect a team. 
Currently, we treat that as a 500 error in the POST /admin/teams/<team_id>/connect endpoint. This PR updates the logic to treat this error (and other similar errors) as 400 errors instead. Under the hood, the Figma REST API returns a 400 error in this case, and we're just bubbling up that error.
Note: In general, the Figma API returns a 400 error if there is no team, the team is deleted, or the user does not have access to the team. 
- I added a unit test.
- I tested the behavior in app.
Note that I kept the UI the same. The existing UI message seems reasonable enough, but open to tweaking if need be in a separate PR.
before | after
--- | ---
=> Fix 4xx error handling in the connect teams endpoint

src/infrastructure/figma/figma-service.ts, src/usecases/disassociate-design-use-case.test.ts, src/usecases/disassociate-design-use-case.ts, src/web/routes/entities/integration.test.ts
Uses a stub design with updateSequenceNumber = 0 to remove the issue association in the disassociate design use case. This removes the dependency on fetching the Figma design for the disassociate use case which fixes the bug when the design has been deleted.
In the future we would like to provide an API to allow removing the issue association without sending any design data which will allow removal of the design stub.
=> FABB-69 Remove Figma dependency from disassociate design use case

scripts/start-sandbox.sh
We run integration tests in the CI pipeline before we build the docker container - [see the Github workflow](https://github.com/atlassian-labs/figma-for-jira/blob/0e831bb5de24d88fb31388cdfa3a090ba94777f8/.github/workflows/actions.yml#L30). The integration tests calls `scripts/start-sandbox.sh`. 
I notice that `prisma migrate dev` has a side-effect. Per [the Prisma docs](https://www.prisma.io/docs/concepts/components/prisma-migrate/migrate-development-production#:~:text=If%20it%20detects%20changes%20to,new%20migration%20from%20these%20changes): If `prisma migrate dev` detects a change to the Prisma schema, it generates a new migration file from these changes.
This resulted in some spooky behavior on our end:
- Our database schema is a bit different from the one in schema.prisma since it's …
=> [ci] Remove side effect of integration tests

src/domain/entities/figma-design-identifier.test.ts, src/domain/entities/figma-design-identifier.ts, src/usecases/associate-design-use-case.test.ts, src/usecases/associate-design-use-case.ts, src/usecases/backfill-design-use-case.test.ts, src/usecases/backfill-design-use-case.ts
Suppose you have a project URL like https://www.figma.com/files/project/176167247/Team-project?fuid=1166427116484924636
Suppose you go to a Jira issue > Link a design URL. Currently, this causes a 500 error in POST /entities/associateEntity.
This PR updates the error handling so we correctly log it as a 400 error.
Ticket: https://figlassian.atlassian.net/browse/FABB-72
- I added unit tests
- I tested locally
before | after
--- | ---
=> FABB-72: Fix error handling for invalid file URLs

admin/src/pages/teams/connect-teams-success-screen.tsx
The success screen looked bad when people connected teams with long names. This PR fixes that
Before: 
After:
=> FABB-42: Fix admin success screen long team name

src/infrastructure/jira/jira-service.test.ts, src/infrastructure/jira/jira-service.ts, src/web/middleware/jira/jira-admin-only-auth-middleware.ts
See: https://figlassian.atlassian.net/browse/FABB-75
We see some number of 500 errors in the GET /admin endpoint. The root cause is a 403 error in the jira-service isAdmin check.
This PR adds error handling for the isAdmin check. That way, if there's a 403 error, we can map that to a 401 error in the top-level endpoint.
- I added unit tests.
=> FABB-75: Add error handling for the isAdmin method

src/infrastructure/jira/jira-client/jira-client.test.ts, src/infrastructure/jira/jira-client/jira-client.ts, src/infrastructure/jira/jira-service.test.ts, src/infrastructure/jira/jira-service.ts, src/usecases/installed-use-case.test.ts, src/usecases/installed-use-case.ts, src/usecases/uninstalled-use-case.test.ts, src/usecases/uninstalled-use-case.ts, src/web/routes/lifecycle-events/integration.test.ts, src/web/testing/jira-api-mocks.ts
Delete the 'is-configured' app property key in jira cloud when the f4j app is uninstalled
This is to set the configured state to 'NOT_SET' when a user uninstalls so the state does not persist across installations
The complexity to add this to the /install flow is not worth it. If the app property deletion fails on uninstall I imagine this would be quite rare and could be dealt with in future if it does become a problem.
=> Reset app configuration state on install/uninstall

src/common/string-utils.test.ts, src/common/string-utils.ts, src/infrastructure/jira/jira-service.test.ts, src/infrastructure/jira/jira-service.ts
We are getting some 500 errors in the endpoint POST /entities/associateEntity. It looks like sometimes, the display name is too long, and we get a validation error. See stack trace.
I think in this case, it's better for us to handle the error gracefully vs. returning a 400 response code. 
The other option here would be to handle the truncation / displayName length validation on the Jira side in the submitDesigns method.
- I added a unit test for this case.
=> [jira-service] Truncate long display names

Dockerfile
Update the base node version for building the application to a newer version which includes a vuln patch for perl.
Current perl version with critical vuln: **5.36.0-7**
After updating the base image, the version will be: **5.36.0-7+deb12u1** which patches the vuln.
=> VULN-1137964 Update the base node image

src/web/middleware/jira/index.ts, src/web/middleware/jira/jira-context-symmetric-jwt-from-query-auth-middleware.ts, src/web/middleware/jira/jira-query-symmetric-jwt-auth-middleware.ts, src/web/routes/router.ts, src/web/routes/static/index.ts, src/web/routes/static/static-router.ts
We got a ticket from atlassian's security team RE: returning <400 status for https://figma-for-jira.figma.com/static/admin and https://figma-for-jira.figma.com/static/issue-panel/issue-panel.html when passed invalid jwts
This is a non-issue since we're not doing any server-side rendering on these routes and subsequent requests do perform JWT validation.
But it doesn't hurt to validate the token before serving these static html files
- Assert that the legacy and admin config page still work
- Deploy on staging first and verify that everything still works before deploying to prod
=> AMS-26036: Update static routes to perform jwt validation

src/jobs/submit-full-design.test.ts, src/jobs/submit-full-design.ts, src/usecases/backfill-design-use-case.test.ts, src/usecases/backfill-design-use-case.ts, src/web/routes/entities/integration.test.ts
- **refactor:** Updates the `submitFullDesign` job not to handle associations. The job is responsible only for design metadata submission -- an association is submitted exclusively by the caller (e.g., `backfillDesignUseCase`). The change allows to simplify the job and avoid race conditions in edge cases.
=> NONE: Update the `submitFullDesign` job not to handle associations

src/common/string-utils.test.ts, src/common/string-utils.ts, src/common/testing/utf16-str.js
Some strings have a different length in utf-8 vs. utf-16 encoding. Javascript strings are utf-16, but Jira expects utf-8 strings. This PR fixes the truncate function to first encode JS strings as UTF8 before truncating.
I wrote a test that fails before the change and passes afterward. Test result against master for reference.
=> Update truncate string util to handle utf-16 / utf-8 strings

scripts/make-tunnel.sh
- **chore:** Update ngrok from 2.x to 3.x to resolve a connection issue. According to the [ngrok docs](https://ngrok.com/blog-post/deprecation-agent-version-3-1), "Free accounts using agents running on 3.1 or older will no longer connect to ngrok".
- Update the setup to use the official [ngrok/ngrok](https://ngrok.com/docs/using-ngrok-with/docker/) Docker container instead of unmaintained [wernight/ngrok](https://github.com/wernight/docker-ngrok).
=> NONE: Update ngrok to v3.x

src/common/string-utils.test.ts, src/common/string-utils.ts, src/common/testing/utf16-str.js, src/domain/entities/atlassian-design.ts, src/infrastructure/figma/figma-backfill-service.test.ts, src/infrastructure/figma/figma-backfill-service.ts, src/infrastructure/figma/figma-client/testing/mocks.ts, src/infrastructure/figma/transformers/figma-file-meta-transformer.test.ts, src/infrastructure/figma/transformers/figma-file-meta-transformer.ts, src/infrastructure/figma/transformers/figma-file-transformer.test.ts, src/infrastructure/figma/transformers/figma-file-transformer.ts, src/infrastructure/figma/transformers/figma-node-transformer.test.ts, src/infrastructure/figma/transformers/figma-node-transformer.ts, src/infrastructure/figma/transformers/utils.test.ts, src/infrastructure/figma/transformers/utils.ts, src/infrastructure/jira/jira-design-service.test.ts, src/infrastructure/jira/jira-design-service.ts
- **fix:** Resolves the issue with `AtlassianDesign` with a not truncated `displayName` being returned from the `/entities/associateEntity` endpoint (and causing the failure in the upstream service). Truncates `AtlassianDesign.displayName` on _the entry points_ to the application to ensure a consistent truncation among use cases.
- **fix:** Resolves the issue with `AtlassianDesign.displayName` being truncates based on bytes instead of UTF-16 code units (as expected by Jira).
- **feat:** Improves the `truncate` utility method to exclude lone surrogates that can appear due to the truncation (e.g., when "🐱", which contains 2 code units, to 1).
=> MDTZ-1571: Resolve the issue with an inconsistent `AtlassianDesign.displayName` truncation

src/domain/entities/figma-design-identifier.test.ts, src/domain/entities/figma-design-identifier.ts, static/issue-panel/issue-panel.js
we're adding `/design` and `/board` where `/file` used to be, so update our url parsing accordingly
- Try to link a design or figjam file with this new path
- Assert that it works
=> NONE: Add support for new figma file urls

src/domain/entities/figma-design-identifier.test.ts, src/domain/entities/figma-design-identifier.ts, src/infrastructure/figma/figma-backfill-service.test.ts, src/infrastructure/figma/figma-backfill-service.ts, src/infrastructure/figma/transformers/figma-file-meta-transformer.ts
This PR re-adds support for branch file URLs. This is the short term approach outlined in https://figlassian.atlassian.net/wiki/spaces/FCS/pages/55115777/Supporting+Branching+in+Figma+for+Jira
We're not making any separate format / tracking branch file keys separately in the app. This will simply update the url parsing to prefer the branch file key over the main file key and use that when appropriate
- Try to associate a branch file URL and see that the embed that shows up points to the branch file
- Try to associate a normal file URL and see that the embed that shows up points to the file
=> NONE: Add support for branch file urls

src/infrastructure/figma/figma-client/schemas.ts, src/infrastructure/figma/figma-client/testing/mocks.ts, src/infrastructure/figma/figma-client/types.ts, src/infrastructure/figma/figma-service.test.ts, src/infrastructure/figma/transformers/figma-file-meta-transformer.test.ts, src/infrastructure/figma/transformers/figma-file-meta-transformer.ts, src/infrastructure/figma/transformers/figma-file-transformer.test.ts, src/infrastructure/figma/transformers/figma-file-transformer.ts, src/infrastructure/figma/transformers/figma-node-transformer.test.ts, src/infrastructure/figma/transformers/figma-node-transformer.ts, src/web/routes/entities/integration.test.ts
We started seeing logs / 500 errors on `POST /associate/entities` because we were failing the schema validation for `GetFileMetaResponse`.
This is because `last_touched_by` can be `null` (eg. the user has since been deleted) which is different from the field being optional
This PR updates the app to be able to handle when `GetFileMetaResponse[file][last_touched_by]` is `null` and adds an integration test to check that this is handled properly
- Revert all changes except for the integration test and assert that the integration test fails
- Apply the changes in this PR and assert that the integration test passes
=> NONE: Update last_touched_by schema validation to be nullable

src/infrastructure/figma/figma-service.ts, src/usecases/associate-design-use-case.test.ts, src/usecases/associate-design-use-case.ts
Describe:
We're currently getting a lot of 500 error alerting when users are inputing design URLs with invalid node ids. For example: `https://www.figma.com/design/<file_key>/<file_name>?node-id=0-a`. When this happens, Figma's REST API returns a 400 w a response like: `ID 0:a is not a valid node_id` in `response.err`.
This PR:
- updates the functions calling `figmaClient.getFile()` to parse the `BadRequestHttpClientError` and throw an `InvalidInputFigmaServiceError`
- updates `associateDesignUseCase` to throw an `InvalidInputUseCaseResultError` when receiving an `InvalidInputFigmaServiceError` (`submit-full-design` and `handle-figma-file-update-event-use-case` don't need their error handling to be updated :D)
- Try attaching an invalid url to an issue
- Assert in the dev console that the …
=> NONE: return 400s when receiving invalid node ids

src/infrastructure/figma-backward-integration-service.test.ts, src/infrastructure/figma-backward-integration-service.ts, src/infrastructure/jira/errors.ts, src/infrastructure/jira/jira-design-issue-property-service.test.ts, src/infrastructure/jira/jira-design-issue-property-service.ts, src/infrastructure/jira/jira-issue-service.test.ts, src/infrastructure/jira/jira-issue-service.ts, src/infrastructure/jira/jira-service.ts
The PR includes the changes extracted from another working branch for reducing the scope of changes and code review convenience.
- **refactor:** Improves the `JiraDesignIssuePropertyService` contract: 
- Updates  API to accept the minimal required data (`url` and `displayName`) instead of the whole `AtlassianDesign`. This is required for the coming changes as a whole `AtlassianDesign` might not be available in all the use cases.
- Improve naming of the methods to reflect better their responsibilities.
- **refactor:** Improves the `JiraIssueService` contract:
- Returns `null` instead of throwing an exception when an Issue is not found. This forces service consumers to handle this common use case and is consistent with other services.
=> MDTZ-1749: Improve the contract of `JiraDesignIssuePropertyService`

Dockerfile
https://asecurityteam.atlassian.net/browse/VULN-1313552 
Vulnerability is due to the Docker base image used (node:20.12.2-bookworm-slim), which uses `debian/systemd 252.22-1~deb12u1` ([reference](https://hub.docker.com/layers/library/node/20.12.2-bookworm-slim/images/sha256-61117b8169f1efa1c1e91c1ed01e8bfcc3ba79ceaaff2cbfcfc370f21e39046f?context=explore))
We need to bump this Docker base image up to node:20.15.0-bookworm-slim, which is the closest version that uses `debian/systemd 252.26-1~deb12u2` ([reference](https://hub.docker.com/layers/library/node/20.15.0-bookworm-slim/images/sha256-d71e0d460434ef500c6d962bcdc6ebe717e5939025dd8aa9746dd76fa12ee6e3?context=explore)), which is enough to fix the VULN, as the VULN suggests:
> Typically updating "systemd" to version `"252.23-1~deb12u1"` …
=> HL-812 Bump node Docker base image to 20.15.0-bookworm-slim for VULN-1313552

src/infrastructure/jira/jira-client/schemas.ts, src/infrastructure/jira/jira-client/testing/mocks.ts, src/infrastructure/jira/jira-client/types.ts, src/infrastructure/jira/jira-design-service.test.ts, src/infrastructure/jira/jira-design-service.ts
This PR fixes the 500s we're seeing when associating designs in Jira. It looks like the response we're getting back changed and as a result of us failing the schema validation, we were throwing 500s in the route.
This PR updates the response schema type to the new values we're seeing
=> NONE: Fix submit design response schema validation

.env.example, .env.test, scripts/start-sandbox.sh, scripts/stop-sandbox.sh
- **chore:** Updates `.env.example` and `.env.test` with the app key matching the official version of the app in Atlassian Marketplace. While any app key can be used with no limitations fo development and testing, the usage of the official one will help to get the full integration experience (incl. some advance secondary features in Jira) during testing.
- **ci:** Resolves the issue with a [failing CI](https://github.com/atlassian-labs/figma-for-jira/actions/runs/10313859962/job/28551326902) due to external changes. Please, see for more detail: https://github.com/actions/runner-images/issues/10384.
=> NONE: Update the app key for local development

src/infrastructure/jira/errors.ts, src/infrastructure/jira/jira-design-issue-property-service.test.ts, src/infrastructure/jira/jira-design-issue-property-service.ts, src/web/routes/entities-v2/integration.test.ts
We're currently 500ing in `PUT /entities/onEntityAssociated` when `jiraClient.setIssueProperty` 404s (eg. the issue was deleted or the user doesn't have the permission to view the issue)
I believe in this case it's ok to no-op on these calls similar to when we get a 403
- unit and integration tests pass
=> NONE: handle when the issue has been deleted or the user is not able to view the issue

package-lock.json, package.json, src/infrastructure/figma/figma-client/figma-client.ts
We were running into `Cannot create a string longer than 0x1fffffe8 characters` errors that we were able to pinpoint to the `response.data` call when calling get file.
This is because the JSON string that gets returned from Figma can be over 512 MB in length. So instead of treating it as a single string, this PR updates that logic so we stream in and build up the JSON object for the file.
- Create a very large file in Figma
- Try to attach the file to an issue
- Previously see that that it throws the error above
- With the changes, see that it's able to successfully parse the file json
- Assert that existing tests pass
=> NONE: fix processing large file jsons from get file

src/web/routes/entities-v2/entities-router.ts, src/web/routes/entities-v2/integration.test.ts, src/web/routes/entities-v2/schemas.ts, src/web/routes/entities-v2/testing/mocks.ts, src/web/routes/entities-v2/types.ts
We are updating POST and PUT APIs to receive all input params in the request body instead of some as the query params. This involves moving the `userId` query param to the body for the following API endpoints:
* getEntityByUrl
* onEntityAssociated
* onEntityDisassociated
This is being done for compatibility reasons on the Atlassian platform which has already been updated to send these values in the body (it is currently sending both query and body params with the query to be removed at a later date).
=> HL-1722 Update mutation APIs to receive userId in body

src/infrastructure/figma/figma-client/figma-client.ts, src/infrastructure/figma/figma-client/testing/mocks.ts, src/web/routes/admin/auth/integration.test.ts, src/web/routes/auth/integration.test.ts, src/web/routes/figma/integration.test.ts
Figma is [encouraging our REST API clients](https://www.figma.com/developers/api#oauth_migration_guide) to use the Basic auth header to transmit OAuth credentials and use token exchange endpoints defined on `api.figma.com`. So this PR makes these updates.
- updated integration tests such that they pass
- unit tests pass
- manually tested authenticating locally
=> NONE: Figma OAuth updates

src/atlassian-connect.ts
"_Figma for Jira_" has used a URL variable to define `userId` query parameter for the `checkAuth` action. However, it has **no functional impact** as the query parameters defined by the specification (like `userId` here) are provided anyway.
The PR removes the usage of a URL variable for query parameters as it adds extra complexity and might be deprecated in the future (due to creating ambiguity in some edge cases).
- **refactor:** Removes an unnecessary usage of URL variables for the `checkAuth` action query parameters.
- The change requires releasing a new version as it affects a Connect descriptor. While it is not urgent, it might be better to do this to avoid mismatch between the source code and runtime.
=> NONE: Remove an unnecessary usage of URL template for the `checkAuth` action

src/config/config.ts
Figma is encouraging our REST API clients to use granular [scopes](https://www.figma.com/developers/api#authentication-scopes), instead of legacy `files:read`. Using more specific scopes helps Figma customers understand what data your app is accessing. In this PR, we use the following granular scopes (`file_content:read,file_metadata:read,current_user:read,projects:read`) to replace `files:read`
*note: disregard the test app name/logo
Before | After
-- | --
- integration tests pass
- unit tests pass
- manually tested authenticating locally
=> NONE: Figma OAuth Scope update

package-lock.json, package.json, src/config/config.ts, src/config/launch_darkly.ts
This PR adds a LaunchDarkly client so that we can feature flag new additions to the integration.
This PR adds the `CLUSTER_NAME` env variable so that we can use the appropriate secret in Figma's different environments. The use of `LAUNCH_DARKLY_SECRET_KEY` for production-like environments and `LAUNCH_DARKLY_SECRET_KEY_MAP` for local development matches how other Figma services connect to LaunchDarkly.
Testing:
- Set up devbox 
- Add some temporary logging in server.ts; make sure flag value correctly aligns with LaunchDarkly value
=> NONE: add launchdarkly feature flagging support
